### PR TITLE
Update dependencies

### LINKED ISSUE #55: semantic-ui-react 2.0.3?
Hello, is this library being maintained? The current version of semantic-ui-react is 2.0.3 but react-semantic-toasts declares a peer dependency compatible with up to 0.88.

### PR DESCRIPTION
**Pull request by Zerquix18**
Fixes #55

### CODE REVIEW

**Comment by Zerquix18** [comment]
Hey @ferrao can you take a look? :)

**Comment by ferrao** [comment]
Sorry it took so long for my to merge it @GGAlanSmithee, I had such a huge github backlog that only today I saw the PR notification....

**Comment by GGAlanSmithee** [comment]
Totally understandable, OS can be a handful, thanks a lot @ferrao and also @Zerquix18 for sending this PR 🥳

**Comment by Zerquix18** [comment]
Any chance this is deployed in npm?

**Comment by ferrao** [comment]
I was just about to @Zerquix18, but when I installed & updated all dependencies locally and tried it I realized something is not right with the styling, as the notifications are occupying all screen witdth:

screenshot

I have zero time to look at it this week, do you want to take a shot at it before I publish a new version?

**Comment by baskin** [comment]
Hi @Zerquix18 , did you get a chance to look at @ferrao 's comment?
I'm too waiting for it to be published on npm.

**Comment by Zerquix18** [comment]
Hi @ferrao 
I have more time now so I decided to take a look.

I set up a local environment to test with the latest CRA and the result of the build and it seems to work normally:

image

This is what I'm rendering:

```

**Comment by ferrao** [comment]
You are correct @Zerquix18, it was a css problem on my side, I have just published v0.6.6 to npm.

**Pull request merged**
