### PR TITLE
Passing props

### LINKED ISSUE #40: 'medium' is not a valid size option
https://github.com/academia-de-codigo/react-semantic-toasts/blob/a6badeb082542e2ca4fa2417353f315258d1e4ae/lib/semantic-toast.jsx#L63 defaults to value `medium` for the size. 
That's not one of the valid choices: https://react.semantic-ui.com/collections/message/#variations-size

```
Warning: Failed prop type: Invalid prop `size` of value `medium` supplied to `Message`, expected one of ["mini","tiny","small","large","big","huge","massive"].
    in Message (created by SemanticToast)
    in SemanticToast (created by SemanticTransition)
    in div (created by SemanticTransition)
    in Transition (created by SemanticTransition)
    in SemanticTransition (created by SemanticToastContainer)
    in div (created by SemanticToastContainer)
    in SemanticToastContainer (at App.js:228)
    in div (at App.js:227)
    in Router (created by BrowserRouter)
    in BrowserRouter (at App.js:226)
    in App (at src/index.js:6)
```

### PR DESCRIPTION
**Pull request by JanKaifer**
Fixed issues with MR #42.

fixes #40

### CODE REVIEW

**Comment by JanKaifer** [comment]
I also thought about removing all `props` that are not modified ie. `onClick`.

**Comment by ferrao** [comment]
@JanKaifer Yes, I think you should remove all props that are not modified or handled specifically in the `SemanticToast` component and just pass them down to the `Message` component and let it handle them.

There is also some conflicts between this branch and master branch, can you please solve those? Also your PR #46 seems to contain the same updates as this one.

**Comment by JanKaifer** [comment]
Yay I forgot to push in #46. It should be ok now.

And I'm also removing all those unchanged props.

**Comment by JanKaifer** [comment]
I have also closed #46 because the issue #40 is fixed removing `size` prop altogether.

**Comment by ferrao** [comment]
Ok, looks good, will merge.

**Pull request merged**
