### PR TITLE
Adding Typescript definition file, adding to build

### PR DESCRIPTION
**Pull request by mstlaurent-paradigm**
Resolves issue #18

### CODE REVIEW

**Comment by ferrao** [comment]
@mstlaurent-paradigm newer versions have aditional toast options, can you please add the missing ones?

**Comment by mstlaurent-paradigm** [comment]
@ferrao Pull request updated

**Comment by ferrao** [comment]
Thank you for your contribution @mstlaurent-paradigm, will update dependencies and publish a new version soon.

**Comment by ferrao** [comment]
@mstlaurent-paradigm `eslint` is throwing the following error on `index.d.ts`:
```
2:5  error  Parsing error: Imports within a `declare module` body must always be `import typ
e` or `import typeof`
```

Do you think you can fix it before I publish a new release?

**Comment by mstlaurent-paradigm** [comment]
Hey @ferrao, I've been looking into this issue, but I can't seem to find a fix. Do you have any suggestions?

**Comment by ferrao** [comment]
No idea @mstlaurent-paradigm, I have zero knowledge of typescript and not very keen on investing time on it just yet ;) 

Have reconfigured `eslint` to target `.js` files only as a workaround and have published a new version.

**Pull request merged**
